require("nhussein11.plugins-setup")

require("nhussein11.core.options")
require("nhussein11.core.keymaps")
require("nhussein11.core.colorscheme")
require("nhussein11.plugins.comment")
require("nhussein11.plugins.nvim-tree")
require("nhussein11.plugins.lualine")
require("nhussein11.plugins.telescope")
require("nhussein11.plugins.nvim-cmp")
require("nhussein11.plugins.lsp.mason")
require("nhussein11.plugins.lsp.lspsaga")
require("nhussein11.plugins.lsp.lspconfig")
require("nhussein11.plugins.lsp.null-ls")
require("nhussein11.plugins.autopairs")
require("nhussein11.plugins.gitsigns")
require("nhussein11.plugins.rust-tools")
